### ISSUE TITLE
Image upload is broken again from 2.2.1+

### ISSUE THREAD

**Issue by ultra-pool** [bitholla/hollaex-kit#1013]
2.2.0 PR was pushed and the image upload was working good. Now after upload to 2.2.1 its been broken and set back to 2MB. 2.2.2 is the same way. This has cause a lot of problems with in the community.

https://github.com/bitholla/hollaex-kit/blob/master/web/src/utils/icon.js#L131
The PR i push had.
`const sizeLimit = sizeLimitInMB * 1024 * 10;`
https://github.com/bitholla/hollaex-kit/pull/981
Look like it was changed back to which put the file size back to 2MB.
`const sizeLimit = sizeLimitInMB * 1024 * 1024;`

**Comment by ultra-pool** [comment]
Would be this better suited for 10MB image upload fix? I have not tested as I needed to reformat my server. But I will test on a clean server. Found that docker was not applying the new image after building.

from `const sizeLimit = sizeLimitInMB * 1024 * 1024;`
To	`const sizeLimit = sizeLimitInMB * 5120 * 5120;`

**Comment by abeikverdi** [comment]
it should be for 10mb:
const sizeLimit = sizeLimitInMB * 1024 * 1024 * 10;

**Comment by ultra-pool** [comment]
I see. Can you push that fix? Or do I need to open another PR? My DIY server docker crashed and had to reformat and no I can redo our test server. It keep saying user already exists and server name already used for our testing. It won't take my user name and password and pull the info from our testing hollaex account.

**Comment by ultra-pool** [comment]
https://github.com/bitholla/hollaex-kit/pull/1026

I was able to test this. Since my DIY hollaex-kit is down ATM. Please verify and add. Thank you for your help abeikverdi

**Comment by ultra-pool** [comment]
Closing since this is in the works. Thank you.

**Comment by ultra-pool** [comment]
I see that was not added to master from dev so reopening this issue.

**Comment by abeikverdi** [comment]
This issue is resolved in v2.2.3 using KYC plugin v6. The KYC related stuff are fully now managed by the KYC plugin v6.

**Comment by ultra-pool** [comment]
Thank you. I will update and test.

**Comment by ultra-pool** [comment]
@abeikverdi kYC v3 plugin gives errors when trying to install. Im not the only one having this error. Please the discord for another user that sent a screenshot.
