### ISSUE TITLE
[Enhancement][Blue panel] Console HTML code add.

### ISSUE THREAD

**Issue by ultra-pool** [bitholla/hollaex-kit#1040]
The current Console your only able to add in header & body. Iv tested both areas and it puts in not so good spots on the exchange. I was wonder if this could be change to be added for the footer area under the TOS/Privacy Policy and powered by area which would make better use of space if your wanting to add partner banners and what not. I just started looking into this late at night. Thoughts on this change?

**Comment by abeikverdi** [comment]
its the HTML head and HTML body which means it covers the entire html. You can control everything through that. Just need to write simple JS code to manipulate the DOM as you want.

**Comment by ultra-pool** [comment]
Thank you. I will update test.
