### ISSUE TITLE
Proper Document Title

### ISSUE THREAD

**Issue by nullart2** [bitholla/hollaex-kit#1284]
I noticed that document.title is not properly shown.

example: 

/wallet should show a "Wallet | <exchang name>" document.title.

Kindly advise how we can do this?

Cheers

**Comment by abeikverdi** [comment]
What do you mean by document.title? You are referring to the html? Since its a Single Page website, you need to render title with JS. You can alternatively change the main index.html which would apply that the entire project.

**Comment by nullart2** [comment]
Thanks for your prompt reply.
