### ISSUE TITLE
/usr/local/bin/hollaex: line 2470 invalid variable name Failed to read pre-bound Activation code.

### ISSUE THREAD

**Issue by csudarshan259** [bitholla/hollaex-kit#1339]
hollaex server --setup

While running this command, after entering login credentials and login verification code I am getting the error.

**Comment by csudarshan259** [comment]
I am trying on windows 11 wsl

**Comment by kycfeel** [comment]
Interesting. Can you share your Bash shell's version here?

Also, the full logs of the error will be helpful.

**Comment by kycfeel** [comment]
@csudarshan259 We were able to reproduce it on our end too. It was an issue that only happens on certain Bash shell versions.

The fix gets just released. You need to install the latest version of CLI.

Simply run `bash install.sh` at your HollaEx Kit directory. That will automatically update your CLI to the latest.

Try the setup again, and let me know If you still face the problem.

Thank you very much.

**Comment by csudarshan259** [comment]
Hi, that issue is solved. I'm getting a new error now.
Error: No such object:  Waiting for the containers to get fully initialized...

**Comment by kycfeel** [comment]
@csudarshan259 Can you show me the full logs?

**Comment by csudarshan259** [comment]
Container : local-palindrome-nginx-1
There are no logs for container : local-palindrome-nginx-1.


Container : local-palindrome-server-api-1
Thu, 07 Apr 2022 06:49:21 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
Thu, 07 Apr 2022 06:49:21 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:21.378Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:21.398Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:21.399Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:21.402Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:21.403Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:21.404Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:21.405Z"}
{"level":"error","message":"app/checkStatus Error  password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:21.486Z"}


Container : local-palindrome-server-plugins-1
Thu, 07 Apr 2022 06:49:45 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
Thu, 07 Apr 2022 06:49:19 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:20.376Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:20.391Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:20.392Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:20.395Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:20.396Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:20.397Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:20.397Z"}
{"level":"error","message":"/plugins/index/initialization err password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:20.406Z"}
Thu, 07 Apr 2022 06:49:27 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:28.760Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:28.772Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:28.773Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:28.775Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:28.776Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:28.776Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:28.777Z"}
{"level":"error","message":"/plugins/index/initialization err password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:28.784Z"}
Thu, 07 Apr 2022 06:49:36 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:37.549Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:37.569Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:37.571Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:37.574Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:37.575Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:37.576Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:37.577Z"}
{"level":"error","message":"/plugins/index/initialization err password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:37.589Z"}
Thu, 07 Apr 2022 06:49:45 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:45.976Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:45.988Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:45.988Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:45.990Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:45.990Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:45.991Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:45.991Z"}
{"level":"error","message":"/plugins/index/initialization err password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:45.998Z"}


Container : local-palindrome-server-stream-1
Thu, 07 Apr 2022 06:49:46 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
Thu, 07 Apr 2022 06:49:20 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"message":"Ẃebsocket server listening on port: 10080 ","level":"verbose","timestamp":"2022-04-07T06:49:20.965Z"}
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:20.970Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:20.980Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:20.980Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:20.982Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:20.983Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:20.984Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:20.984Z"}
{"level":"error","message":"ws/hub/connect/checkStatus Error  password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:20.991Z"}
Thu, 07 Apr 2022 06:49:29 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"message":"Ẃebsocket server listening on port: 10080 ","level":"verbose","timestamp":"2022-04-07T06:49:29.493Z"}
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:29.498Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:29.509Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:29.509Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:29.512Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:29.512Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:29.513Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:29.514Z"}
{"level":"error","message":"ws/hub/connect/checkStatus Error  password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:29.521Z"}
Thu, 07 Apr 2022 06:49:38 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"message":"Ẃebsocket server listening on port: 10080 ","level":"verbose","timestamp":"2022-04-07T06:49:38.453Z"}
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:38.457Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:38.466Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:38.467Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:38.468Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:38.468Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:38.469Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:38.470Z"}
{"level":"error","message":"ws/hub/connect/checkStatus Error  password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:38.475Z"}
Thu, 07 Apr 2022 06:49:46 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
{"message":"Ẃebsocket server listening on port: 10080 ","level":"verbose","timestamp":"2022-04-07T06:49:46.825Z"}
{"level":"verbose","message":"init/checkStatus checking exchange status","timestamp":"2022-04-07T06:49:46.829Z"}
{"message":"Connect to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:46.838Z"}
{"message":"Connect to redis ","level":"verbose","timestamp":"2022-04-07T06:49:46.839Z"}
{"message":"Authenticated to PubSub ","level":"verbose","timestamp":"2022-04-07T06:49:46.840Z"}
{"message":"PubSub is ready ","level":"info","timestamp":"2022-04-07T06:49:46.840Z"}
{"message":"Authenticated to redis ","level":"verbose","timestamp":"2022-04-07T06:49:46.842Z"}
{"message":"Redis is ready ","level":"info","timestamp":"2022-04-07T06:49:46.842Z"}
{"level":"error","message":"ws/hub/connect/checkStatus Error  password authentication failed for user \"hollaex\"","timestamp":"2022-04-07T06:49:46.847Z"}


Container : local-palindrome-redis-1
1:C 07 Apr 2022 06:49:16.642 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Apr 2022 06:49:16.642 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 Apr 2022 06:49:16.642 # Configuration loaded
1:M 07 Apr 2022 06:49:16.643 * monotonic clock: POSIX clock_gettime
1:M 07 Apr 2022 06:49:16.644 * Running mode=standalone, port=6379.
1:M 07 Apr 2022 06:49:16.644 # Server initialized
1:M 07 Apr 2022 06:49:16.644 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 07 Apr 2022 06:49:16.644 * Loading RDB produced by version 6.2.6
1:M 07 Apr 2022 06:49:16.644 * RDB age 16 seconds
1:M 07 Apr 2022 06:49:16.644 * RDB memory usage when created 0.89 Mb
1:M 07 Apr 2022 06:49:16.644 # Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 07 Apr 2022 06:49:16.644 * DB loaded from disk: 0.000 seconds
1:M 07 Apr 2022 06:49:16.644 * Ready to accept connections


Container : local-palindrome-db-1
        Connection matched pg_hba.conf line 95: "host all all all md5"
2022-04-07 06:49:45.995 UTC [35] FATAL:  password authentication failed for user "hollaex"
2022-04-07 06:49:45.995 UTC [35] DETAIL:  Password does not match for user "hollaex".
        Connection matched pg_hba.conf line 95: "host all all all md5"
2022-04-07 06:49:46.844 UTC [36] FATAL:  password authentication failed for user "hollaex"
2022-04-07 06:49:46.844 UTC [36] DETAIL:  Password does not match for user "hollaex".
        Connection matched pg_hba.conf line 95: "host all all all md5"
2022-04-07 06:49:55.233 UTC [37] FATAL:  password authentication failed for user "hollaex"
2022-04-07 06:49:55.233 UTC [37] DETAIL:  Password does not match for user "hollaex".
        Connection matched pg_hba.conf line 95: "host all all all md5"
There are no logs for container : local-palindrome-db-1.

**Comment by csudarshan259** [comment]
@kycfeel I'm not being able to copy secret key from dashboard. Whenever I click copy it does not copy. Instead it copies like this dem********

**Comment by csudarshan259** [comment]
@kycfeel Awaiting your response

**Comment by kycfeel** [comment]
Hey. I'm sure that your local DB's password get messed up. 

Since this is a brand new exchange with no data, I highly recommend you go just terminate it with `hollaex server --terminate` and start over with `hollaex server --setup --force`. 

You need the `--force` flag for the setup cause you already setup the exchange once.

**Comment by csudarshan259** [comment]
@kycfeel how can i become a contributor?
