### ISSUE TITLE
Adding coin issue

### ISSUE THREAD

**Issue by JakeCureton** [bitholla/hollaex-kit#495]
During initial setup, I removed a few assets but left "Bitcoin". Now when clicking next, the error message "You need at least two assets" shows. 
As seen here, https://imgur.com/X28kEaP  the asset box is unclickable and states "no new coin available". 

I also tried to add dogecoin into the list but to no avail. 1. I cannot search for it 2. I have trailed the internet high and low for the contract address, again, no luck. 

UPDATE: If you remove all assets, they appear again. Having only Bitcoin selected displays this message. However, when adding Bitcoin the same occurs and you cannot proceed to add any other crypto.

**Comment by abeikverdi** [comment]
Are you still having this issue? It would be better if you could share a screenshot?

**Comment by abeikverdi** [comment]
Closing this since there hasn't been any recent activities.
