### ISSUE TITLE
Dynamic Strings not showing in Spanish translation

### ISSUE THREAD

**Issue by juanccruz** [bitholla/hollaex-kit#676]
Hi,

There are some stings that contains dynamic programming in English but do not appear in Spanish.

Please see the attached spreadsheet with the specific stings missing.

[Hollaex Localization (to Spanish).xlsx](https://github.com/bitholla/hollaex-kit/files/6297980/Hollaex.Localization.to.Spanish.xlsx)

**Comment by abeikverdi** [comment]
@juanccruz it would be great if you could provide the translation for the missing strings as well

**Comment by juanccruz** [comment]
Will do give me a day or two to translate it.

**Comment by juanccruz** [comment]
@hbeikverdi 
[Hollaex Localization (to Spanish).xlsx](https://github.com/bitholla/hollaex-kit/files/6298721/Hollaex.Localization.to.Spanish.xlsx)
Here is the spreadsheet with the Spanish translation.

**Comment by juanccruz** [comment]
@abeikverdi let me know how can I assist you further more with the translation.

**Comment by abeikverdi** [comment]
This issue is fixed in v2.1

**Comment by juanccruz** [comment]
Thanks!!!
